# The most helpful template in the world -> https://raw.githubusercontent.com/aws-samples/amazon-ec2-nice-dcv-samples/main/cfn/WIndowsServer-NICE-DCV.yaml

AWSTemplateFormatVersion: '2010-09-09'
Description: Remote Windows Desktop for video editing / streaming

Parameters:
  KeyName:
    Description: SSH keypair, used to retrieve admin password 
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.


Resources:

  # Port forwarding / opening
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access

      SecurityGroupIngress:

        - IpProtocol: tcp # SSH access
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp # RDP access
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0

        - IpProtocol: udp # SRT access
          FromPort: 4200
          ToPort: 4200
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: !Ref AWS::StackName



  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: [sts:AssumeRole]
      Policies:
        - PolicyName: gpuDrivers
          PolicyDocument: # https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource:
                  - arn:*:s3:::nvidia-gaming
                  - arn:*:s3:::nvidia-gaming/*
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName


  EC2Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref EC2Role]



  # G4dn.xlarge EC2 instance
  ec2Instance:
    Type: AWS::EC2::Instance

    Metadata:
      Comment: Install Update files
      AWS::CloudFormation::Init:
        configSets:
          setup:
            - 00_setup
          software_install:
            - 01_software_install
          gpu_download:
            - 02_gpu_download

        00_setup:
          files:

            c:\\windows\\temp\\initial-setup.cmd:
              content: |
                @echo off
                powershell -Command "Start-Sleep -s 5"
                IF EXIST c:\windows\temp\initial-setup.txt EXIT
                ECHO started > c:\windows\temp\initial-setup.txt

                @echo ** Clean desktop
                del /q "C:\Users\Administrator\Desktop\*"
                curl -L -o "C:\Users\Administrator\Desktop\BraveBrowser.exe" "https://laptop-updates.brave.com/latest/winx64"

                @echo ** Open port of firewall to allow SRT
                netsh advfirewall firewall add rule name="Allow SRT UDP 4200" dir=in action=allow protocol=UDP localport=4200

                ECHO done >> c:\windows\temp\initial-setup.txt
                exit


          commands: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#aws-resource-init-commands
            install:
              command: c:\windows\temp\initial-setup.cmd >> c:\windows\temp\initial-setup.log
              ignoreErrors: true
              waitAfterCompletion: forever


        01_software_install:
          files:
            c:\\windows\\temp\\software-install.cmd:
              content: !Sub |
                @echo off
                IF EXIST c:\windows\temp\software-install.txt EXIT
                ECHO started > c:\windows\temp\software-install.txt

                powershell -C "Get-EC2InstanceMetadata -Category InstanceId" > c:\windows\temp\instanceid.txt
                set /p INSTANCEID=<c:\windows\temp\instanceid.txt
                net user administrator %INSTANCEID%

                @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

                choco install --no-progress -y awscli
                setx /M AWS_CLI_AUTO_PROMPT on-partial

                ECHO done > c:\windows\temp\software-install.txt
                exit

          commands: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#aws-resource-init-commands
            install:
              command: c:\windows\temp\software-install.cmd >> c:\windows\temp\software-install.log
              ignoreErrors: true
              waitAfterCompletion: forever


        02_gpu_download:
          files:
            c:\\windows\\temp\\download-NVIDIA-Gaming-driver.cmd:
              content: |
                @echo off
                powershell -Command "Start-Sleep -s 5"
                IF EXIST c:\windows\temp\download-NVIDIA-Gaming-driver.txt EXIT
                ECHO started > c:\windows\temp\download-NVIDIA-Gaming-driver.txt

                @echo ** Can't use "aws", need to use full path, maybe issue with PATH ?
                "C:\Program Files\Amazon\AWSCLIV2\aws" s3 cp --recursive s3://nvidia-gaming/windows/latest/ "C:\Users\Administrator\Desktop"

                reg add "HKLM\SYSTEM\CurrentControlSet\Services\nvlddmkm\Global" /v vGamingMarketplace /t REG_DWORD /d 2 /f
                reg add "HKLM\SOFTWARE\NVIDIA Corporation\Global" /v vGamingMarketplace /t REG_DWORD /d 2
                powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://nvidia-gaming.s3.amazonaws.com/GridSwCert-Archive/GridSwCertWindows_2023_9_22.cert', 'C:\Users\Public\Documents\GridSwCert.txt')"

                ECHO done >> c:\windows\temp\download-NVIDIA-Gaming-driver.txt
                exit

          commands: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#aws-resource-init-commands
            install:
              command: c:\windows\temp\download-NVIDIA-Gaming-driver.cmd >> c:\windows\temp\download-NVIDIA-Gaming-driver.log
              ignoreErrors: true



    Properties:
      ImageId: ami-0a61c9559ed98dd19
      InstanceType: g4dn.xlarge
      IamInstanceProfile: !Ref EC2Profile
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref InstanceSecurityGroup

      BlockDeviceMappings: 
        - DeviceName: /dev/sda1 # For C:\ device
          Ebs:
            VolumeSize: 50
            VolumeType: gp3
            DeleteOnTermination: true
        - DeviceName: xvdh
          Ebs:
            VolumeSize: 70
            VolumeType: gp3
            DeleteOnTermination: false

      UserData:
        Fn::Base64: !Sub |
          <script>
          @echo off
          cfn-init.exe -v --stack ${AWS::StackId} --resource ec2Instance --region ${AWS::Region} --configsets setup

          @echo ** install some software 
          cfn-init.exe -v --stack ${AWS::StackId} --resource ec2Instance --region ${AWS::Region} --configsets software_install

          @echo ** install graphics driver
          cfn-init.exe -v --stack ${AWS::StackId} --resource ec2Instance --region ${AWS::Region} --configsets gpu_download

          cfn-signal.exe -e %errorlevel% --stack ${AWS::StackId} --resource ec2Instance --region ${AWS::Region}
          </script>

      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
